import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { SEO_TITLE, SEO_DESCRIPTION } from '@/utils/config'
import BaseHead from '@/components/BaseHead'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <BaseHead 
        title={SEO_TITLE}
        description={SEO_DESCRIPTION}
      />
      <body 
        className={`${inter.className} container`}
      >{children}</body>
    </html>
  )
}
