import Star from './dashboard-main/star.svg'
import Fs from './dashboard-main/franklyspeaking.jpg'
import PlayCircle from './dashboard-main/play-circle.svg'
import TopCategories from './dashboard-main/topcategories.svg'
import Down from './dashboard-main/down.svg'
import Joe from './dashboard-main/joe.svg'
import JoeR from './dashboard-main/joerogan.jpg'
import MarcMaron from './dashboard-main/marcmaron.jpeg'
import Category from './dashboard-main/category.svg'
import HDTGM from './dashboard-main/hdtgm.svg'
import Comedy from './dashboard-main/comedy.svg'
import HF from './dashboard-main/h&f.svg'
import Love from './dashboard-main/love.svg'
import Education from './dashboard-main/education.svg'
import Religion from './dashboard-main/religion.svg'
import Music from './dashboard-main/music.svg'
import Technology from './dashboard-main/technology.svg'
import GP from './dashboard-main/g&p.svg'
import RatingStarColored from './dashboard-main/rating-star-colored.svg'
import RatingStar from './dashboard-main/rating-star.svg'
import LeLove from './dashboard-main/le-love.svg'
import LeHam from './dashboard-main/le-ham.svg'
import LePlus from './dashboard-main/le-plus.svg'
import LeShare from './dashboard-main/le-share.svg'
import LeDownload from './dashboard-main/le-download.svg'

import Discover from './sidenav/discover.svg'
import Top50 from './sidenav/top-50-podcasts.svg'
import Categories from './sidenav/categories.svg'
import AddPodcast from './sidenav/add-your-podcast.svg'
import YourPlaylist from './sidenav/your-playlist.svg'
import RecentlyPlayed from './sidenav/recently-played.svg'
import SH from './sidenav/s&h.svg'
import WokpaPodcasters from './sidenav/wokpa-podcasters.svg'
import WokpaAdvertisers from './sidenav/wokpa-advertisers.svg'
import ReadBlog from './sidenav/read-blog.svg'
import WokpaLogo from './sidenav/wokpalogo.svg'
import SLove from './sidenav/love.svg'
import SHam from './sidenav/ham.svg'
import SPlus from './sidenav/plus.svg'
import Close from './sidenav/close.svg'
import Menu from './sidenav/menu.svg'

import User from './header/user.svg'
import Mobile from './header/mobile.svg'
import Search from './header/search.svg'

import GoogleIcon from './modal/googleIcon.svg'
import CloseIcon from './modal/closeIcon.svg'
import Right from './modal/right.svg'
import FacebookIcon from './modal/facebook.svg'
import AppleIcon from './modal/apple.svg'
import EnvelopeIcon from './modal/envelope.svg'
import DownIcon from './modal/down.svg'

import HeartIcon from './favourites/heart.svg'
import Player from './favourites/player.svg'

import QueueIcon from './queue/queue.svg'
import QueuePlayer from './queue/player.svg'
import QueueHam from './queue/ham.svg'

const Assets = {
    Star, Fs, PlayCircle, TopCategories, Down, Discover, Top50, Categories, AddPodcast, YourPlaylist, RecentlyPlayed, SH, WokpaPodcasters, WokpaAdvertisers, ReadBlog, Joe, MarcMaron, JoeR, Category, HDTGM, Comedy, HF, Love, Education, Religion, Music, Technology, GP, RatingStarColored, RatingStar, LeDownload, LeHam, LeLove, LePlus, LeShare, WokpaLogo, SLove, SHam, SPlus, User, Mobile, Search, Close, Menu, GoogleIcon, CloseIcon, Right, FacebookIcon, AppleIcon, EnvelopeIcon, DownIcon, HeartIcon, Player, QueueIcon, QueuePlayer, QueueHam
}

export default Assets